# Generated by Django 5.2.1 on 2025-06-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_oauth_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
