# Generated by Django 5.2.1 on 2025-06-21 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
