# # # services:
# # #   redis:
# # #     image: redis:7.2
# # #     container_name: edulance_redis
# # #     ports:
# # #       - "6379:6379"
# # #     volumes:
# # #       - redis_data:/data
# # #     restart: unless-stopped

# # # volumes:
# # #   redis_data:

# # services:
# #   redis:
# #     image: redis:7.2
# #     container_name: edulance_redis
# #     ports:
# #       - "6379:6379"
# #     volumes:
# #       - redis_data:/data
# #     restart: unless-stopped

# #   web:
# #     build: .
# #     container_name: edulance
# #     command: python manage.py runserver 0.0.0.0:8000
# #     volumes:
# #       - .:/code
# #     ports:
# #       - "8000:8000"
# #     depends_on:
# #       - redis
# #     env_file:
# #       - .env.docker

# #   celery:
# #     build: .
# #     container_name: edulance_celery
# #     command: celery -A edulance worker --loglevel=info
# #     volumes:
# #       - .:/code
# #     depends_on:
# #       - redis
# #       - web
# #     env_file:
# #       - .env.docker

# #   celery-beat:
# #     build: .
# #     container_name: edulance_celery_beat
# #     command: celery -A edulance beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
# #     volumes:
# #       - .:/code
# #     depends_on:
# #       - redis
# #       - web
# #     env_file:
# #       - .env.docker

# # volumes:
# #   redis_data:
services:
  web:
    build: .
    image: edulance:v-combined
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    image: edulance:v-combined
    command: celery -A edulance_root worker --loglevel=INFO
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
  beat:
    image: edulance:v-combined
    command: celery -A edulance_root beat --loglevel=INFO
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
