services:
  web:
    build: .
    image: edulance:v-combined
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    environment:
      - RUN_MIGRATIONS=true
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    image: edulance:v-combined
    command: celery -A edulance_root worker --loglevel=INFO
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    environment:
      - RUN_MIGRATIONS=false
  beat:
    image: edulance:v-combined
    command: celery -A edulance_root beat --loglevel=INFO
    depends_on:
      - db
      - redis
    environment:
      - RUN_MIGRATIONS=false
    env_file:
      - .env.docker

  redis:
    image: redis:7
    ports:
      - "6379:6379"
