# Generated by Django 5.2.1 on 2025-06-22 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collaborationpost',
            name='activity_type',
            field=models.CharField(choices=[('learning', 'Learning'), ('hackathon', 'Hackathon'), ('group_study', 'Group Study'), ('project', 'Project')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collaborationpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collaborationpost',
            name='required_skills',
            field=models.JSONField(default=list),
        ),
    ]
