# Generated by Django 5.2.1 on 2025-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0002_collaborationpost_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collaborationpost',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='collaborationpost',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='posts', to='collaborate.skill'),
        ),
    ]
