# Generated by Django 5.2.1 on 2025-06-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0003_skill_remove_collaborationpost_required_skills_and_more'),
        ('users', '0004_user_avatar_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AlterField(
            model_name='collaborationpost',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='posts', to='users.skill'),
        ),
    ]
