# Generated by Django 5.2.1 on 2025-06-24 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0004_delete_skill_alter_collaborationpost_required_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationpost',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
