# Generated by Django 5.2.1 on 2025-06-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0005_collaborationpost_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationpost',
            name='activity_type',
            field=models.CharField(choices=[('learning', 'Learning'), ('hackathon', 'Hackathon'), ('project', 'Project')], max_length=20),
        ),
    ]
